apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
  namespace: {{ .Values.Deployment.namespace }}
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: user
---