apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: {{ .Values.Deployment.namespace }}
  {{- if eq .Values.Deployment.target "AKS" }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: sock-frontend
  {{- end }}
spec:
  {{- if eq .Values.Deployment.target "AKS" }}
  loadBalancerIP: {{ .Values.Azure.loadBalancerIP}}
  {{- end }}
  externalTrafficPolicy: Cluster
  ports:
    - port: 8079
  selector:
    name: front-end
  sessionAffinity: None
  type: LoadBalancer