apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: {{ .Values.Deployment.namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32360
    port: 8079
    protocol: TCP
    targetPort: 8079
  selector:
    name: front-end
  sessionAffinity: None
  type: LoadBalancer